# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
paste_actions no-op
paste_actions replace-dangerous-control-codes,replace-newline
clipboard_control write-clipboard write-primary read-clipboard read-primary
# END_KITTY_THEME
